author: Albin
title: Technicalities and other goodies
email: albin@codeindite.com
description: >- # this means to ignore newlines until "baseurl:"
  This is my personal blog where I discuss technical matters.
  Primarily this was created as an assignment, but I might use this blog for future posts as well.
baseurl: "/cloud-course-blog" # the subpath of your site, e.g. /blog
url: "https://albinalm.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: albinalm
github_username:  albinalm

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
